//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CyberToolBox.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CYBERTTYPE                  129
#define IDD_MODULE_CONFIG               133
#define IDD_MODULE_WORLD_PAGE           135
#define IDD_MODULE_MATH_PAGE            136
#define IDD_DIAGRAM_NEW                 139
#define IDC_MODULE_CURSOR               143
#define IDD_WORLDCONSTANT               146
#define IDD_STRING_CONSTANT             146
#define IDI_WORLDCONSTANT               147
#define IDD_MODULE_NUMERIC_PAGE         148
#define IDD_USER_EVENT_TIMER_PAGE       149
#define IDD_USER_EVENT_CLOCK_PAGE       152
#define IDD_MODULE_OBJECT_PAGE          153
#define IDD_OBJECTNAME                  154
#define IDI_OBJECTNAME                  155
#define IDI_OBJECT                      155
#define IDR_DIAGRAM_TOOLBAR             159
#define IDR_DIAGRAM                     159
#define IDD_NODECONFIG                  161
#define IDD_USER_EVENT_PICKUP_PAGE      162
#define IDD_USER_EVENT_DRAG_PAGE        163
#define IDD_GLOBALDATA_NAME             164
#define IDD_MODULE_BOOLEAN_PAGE         165
#define IDD_MODULE_MISC_PAGE            166
#define IDB_ROOT                        168
#define IDB_NODE                        169
#define IDB_DIAGRAM                     170
#define IDR_PERSPECTIVE                 171
#define IDC_PICKING_CURSOR              174
#define IDB_SCENEGRAPH                  175
#define IDB_EVENT                       176
#define IDB_EVENTROOT                   177
#define IDD_MODULE_VIEW_PAGE            180
#define IDD_VIEW_NAME                   181
#define IDI_VIEW                        184
#define IDI_LIGHT                       185
#define IDD_MODULE_LIGHT_PAGE           186
#define IDD_MODULE_MATERIAL_PAGE        187
#define IDD_MATERIAL_NAME               188
#define IDD_LIGHT_NAME                  189
#define IDI_MATERIAL                    192
#define IDD_DIAGRAM                     193
#define IDD_USER_EVENT_AREA             195
#define IDD_USER_EVENT_COLLISION_PAGE   196
#define IDD_PROGRESS                    197
#define IDR_ORTHOVIEW                   198
#define IDD_NODE_NEW                    200
#define IDB_ANCHOR                      202
#define IDB_BILLBOARD                   203
#define IDB_COLLISION                   204
#define IDB_GROUP                       205
#define IDB_TRANSFORM                   207
#define IDB_INLINE                      208
#define IDB_LOD                         209
#define IDB_SWITCH                      210
#define IDB_AUDIOCLIP                   211
#define IDB_DLIGHT                      212
#define IDB_PLIGHT                      213
#define IDB_SCRIPT                      214
#define IDB_SHAPE                       215
#define IDB_SOUND                       216
#define IDB_SLIGHT                      217
#define IDB_WORLDINFO                   218
#define IDB_CYLINDERSENSOR              219
#define IDB_PLANESENSOR                 220
#define IDB_SPHERESENSOE                221
#define IDB_SPHERESENSOR                221
#define IDB_PROXIMITYSENSOR             222
#define IDB_TIMESENSOR                  224
#define IDB_TOUCHSENSOR                 225
#define IDB_VISIVILITYSENSOR            226
#define IDB_VIEWPOINT                   227
#define IDB_BOX                         228
#define IDB_CONE                        229
#define IDB_CYLINDER                    230
#define IDB_ELEVATIONGRID               231
#define IDB_EXTRUSION                   232
#define IDB_IDXFACESET                  233
#define IDB_IDXLINESET                  234
#define IDB_POINTSET                    235
#define IDB_SPHERE                      236
#define IDB_TEXT                        237
#define IDB_COLOR                       238
#define IDB_COORDINATE                  239
#define IDB_NORMAL                      240
#define IDB_TEXCOORD                    241
#define IDB_IMAGETEXTURE                242
#define IDB_PIXELTEXTURE                243
#define IDB_APPEARANCE                  244
#define IDB_FONTSTYLE                   245
#define IDB_MATERIAL                    246
#define IDB_MOVIETEXTURE                247
#define IDB_TEXTRANSFORM                248
#define IDB_COLORINTERP                 249
#define IDB_COORDINTERP                 250
#define IDB_NORMALINTERP                251
#define IDB_ORIENTATIONINTERP           252
#define IDB_POSITIONINTERP              253
#define IDB_SCALARINTERP                254
#define IDB_BACKGROUND                  255
#define IDB_FOG                         256
#define IDB_NAVIGATIONINFO              257
#define IDD_SFBOOL                      260
#define IDD_SFROTATION                  261
#define IDD_SFVEC3F                     262
#define IDD_SFVEC2F                     263
#define IDD_SFFLOAT                     265
#define IDD_SFINT32                     266
#define IDD_SFSTRING                    267
#define IDD_MFIELD                      268
#define IDD_ORTHVIEWCONFIG              269
#define IDD_SFTIME                      270
#define IDI_ICON1                       271
#define IDI_MISC_PLAYSOUND              271
#define IDD_EVENT_FRAME                 272
#define IDD_EVENT_AREA                  273
#define IDD_EVENT_PICKUP                274
#define IDD_EVENT_CLOCK                 275
#define IDD_ORTHVIEW_CONFIG             277
#define IDD_DIAGRAM_CONFIG              278
#define IDD_MODULE_FILTER_PAGE          279
#define IDD_MODULE_FILTER_LOW           281
#define IDD_MODULE_FILTER_HIGH          282
#define IDD_MODULE_FILTER_RANGE         283
#define IDD_MODULE_FILTER_SCALE         284
#define IDI_FILTER_SCALE                285
#define IDI_FILTER_RANGE                286
#define IDI_FILTER_HIGH                 287
#define IDI_FILTER_LOW                  288
#define IDB_PRIMITIVE_SPHERE            289
#define IDB_PRIMITIVE_CONE              290
#define IDB_PRIMITIVE_BOX               291
#define IDB_PRIMITIVE_CYLINDER          292
#define IDD_PRIMITIVE                   293
#define IDC_PRIMITIVE_CURSOR            294
#define IDD_OBJECTNAME_2                296
#define IDB_PRIMITIVE_POLYGON           300
#define IDC_PICK                        301
#define IDB_PRIMITIVE_TEXT              302
#define IDC_PRIMITIVE_SPHERE            303
#define IDC_PRIMITIVE_BOX               304
#define IDC_PRIMITIVE_CONE              305
#define IDC_PRIMITIVE_CYLINDER          306
#define IDC_PRIMITIVE_POLYGON           307
#define IDC_PRIMITIVE_TEXT              309
#define IDC_OBJECT_SCALE                310
#define IDC_OBJECT_TRANSLATE            311
#define IDC_ZOOM                        312
#define IDC_OBJECT_ROTATE               313
#define IDD_OBJECT_APPEARANCE           314
#define IDD_MODULE_STRING_POSITION      315
#define IDD_MODULE_STRING_VECTOR        316
#define IDD_MODULE_STRING_ORIENTATION   318
#define IDD_MODULE_FILTER_P2DINTERP     319
#define IDD_MODULE_FILTER_P3DINTERP     320
#define IDD_MODULE_FILTER_ORIINTERP     321
#define IDD_MODULE_FILTER_SCALAINTERP   322
#define IDD_MODULE_MISC_PLAYSOUND       323
#define IDD_EVENT_TIMER                 326
#define IDD_USER_EVENT_TIMER            327
#define IDD_PERSPECTIVE_CONFIG          333
#define IDD_EVENT_DRAG                  334
#define IDD_STRING_BOOL                 335
#define IDR_ORTHOVIEW_POPUP             336
#define IDR_PERSPECTIVEVIEW_POPUP       339
#define IDB_ROUTE                       341
#define IDB_ROUTE_ROOT                  342
#define IDD_ROUTE_CONFIG                343
#define IDD_MODULE_NODE_PAGE            344
#define IDD_MODULE_INTERP_PAGE          345
#define IDD_MODULE_INTERP_COLOR         346
#define IDI_INTERP_COLOR                349
#define IDI_INTERP_POSITION             350
#define IDI_INTERP_ORIENTATION          351
#define IDI_INTERP_NORMAL               352
#define IDI_INTERP_SCALAR               353
#define IDD_MODULE_INTERP_POSITION      354
#define IDD_MODULE_INTERP_ORIENTATION   356
#define IDD_MODULE_INTERP_SCALAR        358
#define IDD_MODULE_INTERP_NORMAL        360
#define IDD_TEXT_NAME                   362
#define IDI_TEXT                        363
#define IDD_BACKGROUND_NAME             365
#define IDI_BACKGROUND                  367
#define IDI_IMAGETEXTURE                368
#define IDD_IMAGETEXTURE_NAME           369
#define IDI_SWITCH                      371
#define IDD_SWITCH                      372
#define IDI_AUDIOCLIP                   374
#define IDD_AUDIOCLIP                   375
#define IDD_MODULE_GEOM_PAGE            377
#define IDR_TOOLBAR1                    378
#define IDC_CLASS_NAME                  1005
#define IDC_EVENTIN_TYPE1               1010
#define IDC_EVENTIN_TYPE2               1011
#define IDC_EVENTIN_TYPE3               1012
#define IDC_EVENTIN_TYPE4               1013
#define IDC_EVENTOUT_TYPE1              1014
#define IDC_EVENTOUT_TYPE2              1015
#define IDC_EVENTOUT_TYPE3              1016
#define IDC_EVENTOUT_TYPE4              1017
#define IDC_EVENTIN_NAME1               1018
#define IDC_EVENTIN_NAME2               1019
#define IDC_EVENTIN_NAME3               1020
#define IDC_EVENTIN_NAME4               1021
#define IDC_EVENTOUT_NAME1              1022
#define IDC_EVENTOUT_NAME2              1023
#define IDC_EVENTOUT_NAME3              1024
#define IDC_EVENTOUT_NAME4              1025
#define IDC_MODULE_NAME                 1028
#define IDC_SCRIPT_SELECT               1030
#define IDC_SCRIPT_NAME                 1031
#define IDC_MODULE_ICON                 1032
#define IDC_MODULE_ICON_SELECT          1033
#define IDC_SCROLLBAR1                  1034
#define IDC_DIFFUSE_RCOLOR              1034
#define IDC_DIFFUSE_GCOLOR              1035
#define IDC_DIFFUSE_BCOLOR              1036
#define IDC_SPECULAR_RCOLOR             1037
#define IDC_MODULE_ADD                  1038
#define IDC_SPECULAR_GCOLOR             1038
#define IDC_MODULE_CONFIG               1039
#define IDC_SPECULAR_BCOLOR             1039
#define IDC_MODULE_DELETE               1040
#define IDC_EMISSIVE_RCOLOR             1040
#define IDC_BOOLEAN_NODE                1041
#define IDC_EXECUTION_NODE              1041
#define IDC_EMISSIVE_GCOLOR             1041
#define IDC_MODULE_ICON_NAME            1042
#define IDC_EMISSIVE_BCOLOR             1042
#define IDC_MODULE_LIST                 1045
#define IDC_DIAGRAM_EVENTTYPENAME       1046
#define IDC_DIAGRAM_NAME                1047
#define IDC_EVENTIN_ACTIVE1             1050
#define IDC_EVENTIN_ACTIVE2             1051
#define IDC_EVENTIN_ACTIVE3             1052
#define IDC_EVENTIN_ACTIVE4             1053
#define IDC_EVENTOUT_ACTIVE1            1054
#define IDC_EVENTOUT_ACTIVE2            1055
#define IDC_EVENTOUT_ACTIVE3            1056
#define IDC_EVENTOUT_ACTIVE4            1057
#define IDC_VALUE                       1062
#define IDC_INTREVAL_TIME               1063
#define IDC_MAX_VALUE                   1063
#define IDC_INTREVAL_TIME_SPIN          1064
#define IDC_OBJECTNAME                  1074
#define IDC_NODEFIELD                   1075
#define IDC_NODENAME                    1076
#define IDC_OBJECT_NAME1                1076
#define IDC_NODE_NAME                   1077
#define IDC_FIELD_NAME                  1078
#define IDC_GLOBALDATA_NAME             1079
#define IDC_FIELD_NAME2                 1079
#define IDC_VIEW_NAME                   1080
#define IDC_NODE_NAME2                  1080
#define IDC_MATERIAL_NAME               1082
#define IDC_LIGHT_NAME                  1083
#define IDC_OPEN                        1084
#define IDC_COLLISION_CENTER            1086
#define IDC_COLLISION_SIZE              1087
#define IDC_NODE_NAME1                  1088
#define IDC_FIELD_COLLISION_CENTER      1089
#define IDC_FIELD_COLLISION_SIZE        1090
#define IDC_FIELD_NAME1                 1091
#define IDC_PROGRESS                    1092
#define IDC_NODE_LIST                   1093
#define IDC_MODULE_IMAGELIST            1097
#define IDC_IMAGELIST_SCROLLBAR         1098
#define IDC_TRUE_RADIO                  1100
#define IDC_FALSE_RADIO                 1101
#define IDC_XVALUE                      1102
#define IDC_RVALUE                      1103
#define IDC_XVALUE2                     1103
#define IDC_YVALUE                      1104
#define IDC_ZVALUE                      1105
#define IDC_XSPIN                       1106
#define IDC_YSPIN                       1107
#define IDC_SFVALUE_LIST                1107
#define IDC_ZSPIN                       1108
#define IDC_RSPIN                       1109
#define IDC_SPIN1                       1109
#define IDC_YVALUE2                     1109
#define IDC_SPIN2                       1110
#define IDC_ZVALUE2                     1110
#define IDC_EDIT1                       1111
#define IDC_XSPIN2                      1111
#define IDC_RVALUE2                     1111
#define IDC_EDIT2                       1112
#define IDC_YSPIN2                      1112
#define IDC_VALUE_SPIN                  1113
#define IDC_CENTER_Z                    1113
#define IDC_ZSPIN2                      1113
#define IDC_TIME_SPIN                   1114
#define IDC_SIZE_X                      1114
#define IDC_SLIDER1                     1115
#define IDC_SIZE_Y                      1115
#define IDC_SIZE_Z                      1116
#define IDC_CX_STATIC                   1117
#define IDC_RSPIN2                      1117
#define IDC_CY_STATIC                   1118
#define IDC_CZ_STATIC                   1119
#define IDC_SX_STATIC                   1120
#define IDC_SY_STATIC                   1121
#define IDC_SZ_STATIC                   1122
#define IDC_SIZE_STATIC                 1123
#define IDC_CENTER_STATIC               1124
#define IDC_CENTER_X                    1125
#define IDC_CENTER_Y                    1126
#define IDC_TIMESLIDER                  1127
#define IDC_TIMESTRING                  1128
#define IDC_UNITSTRING                  1129
#define IDC_FRAMESTRING                 1130
#define IDC_CHECK2                      1135
#define IDC_SNAP                        1135
#define IDC_CHECK3                      1136
#define IDC_GRID_DISPLAY                1136
#define IDC_DISPLAY_SHAPE               1137
#define IDC_DISPLAY_POINTLIGHT          1138
#define IDC_DISPLAY_SPOTLIGHT           1139
#define IDC_DISPLAY_VIEWPOINT           1140
#define IDC_DISPLAY_AXIS                1141
#define IDC_DISPLAY_GRID                1142
#define IDC_STEP_POSITION               1143
#define IDC_STEP_ANGLE                  1144
#define IDC_SPIN_POSITION               1145
#define IDC_SPIN_ANGLE                  1146
#define IDC_MIN_VALUE                   1147
#define IDC_GRID_SNAP                   1149
#define IDC_LINE_TYPE                   1152
#define IDC_OBJECT2_NAME                1154
#define IDC_OBJECT1_NAME                1155
#define IDC_OBJECT1_RADIUS              1156
#define IDC_OBJECT2_RADIUS              1157
#define IDC_OBJECT1_NAME_STRING         1158
#define IDC_OBJECT2_NAME_STRING         1159
#define IDC_OBJECT1_RADIUS_STRING       1160
#define IDC_OBJECT2_RADIUS_STRING       1161
#define IDC_OBJECT_NAME2                1162
#define IDC_OBJECT_RADIUS1              1163
#define IDC_OBJECT_RADIUS2              1164
#define IDC_AMBIENT_INTENSITY           1170
#define IDC_SHININESS                   1171
#define IDC_XVALUE1                     1172
#define IDC_TRANSPARENCY                1172
#define IDC_YVALUE1                     1173
#define IDC_ZVALUE1                     1174
#define IDC_XSPIN1                      1175
#define IDC_YSPIN1                      1176
#define IDC_ZSPIN1                      1177
#define IDC_VALUE2                      1178
#define IDC_XSPIN3                      1178
#define IDC_VALUE1                      1179
#define IDC_RVALUE1                     1180
#define IDC_RSPIN1                      1181
#define IDC_AUDIOCLIP_NAME              1182
#define IDC_WAKEUP_TIME                 1186
#define IDC_ADD                         1191
#define IDC_DELETE                      1192
#define IDC_INSERT                      1193
#define IDC_WIREFRAME                   1194
#define IDC_SHADING                     1195
#define IDC_TEXTURE                     1196
#define IDC_NAVIGATIONINFO_SPEED        1197
#define IDC_NAVIGATIONINFO_HEADLIGHT    1198
#define IDC_SPIN_NAVIGATIONINFO_SPEED   1199
#define IDC_DIFFUSE_RCOLOR_VALUE        1200
#define IDC_DIFFUSE_GCOLOR_VALUE        1201
#define IDC_DIFFUSE_BCOLOR_VALUE        1202
#define IDC_EMISSIVE_RCOLOR_VALUE       1203
#define IDC_EMISSIVE_GCOLOR_VALUE       1204
#define IDC_EMISSIVE_BCOLOR_VALUE       1205
#define IDC_SPECULAR_RCOLOR_VALUE       1206
#define IDC_SPECULAR_GCOLOR_VALUE       1207
#define IDC_SPECULAR_BCOLOR_VALUE       1208
#define IDC_APPLY                       1209
#define IDC_AMBIENT_INTENSITY_VALUE     1210
#define IDC_SHININESS_VALUE             1211
#define IDC_TRANSPARENCY_VALUE          1212
#define IDC_TEXTURE_SELECT              1214
#define IDC_TEXTURE_WIDTH               1215
#define IDC_TEXTURE_HEIGHT              1216
#define IDC_TEXTURE_FORMAT              1217
#define IDC_TEXTURE_DELETE              1218
#define IDC_LICENCECODE                 1220
#define IDC_SET_LICENCE_CODE            1222
#define IDC_SOFTWARE_PRODUCT_ID         1223
#define IDC_UNIT_DEGREE                 1225
#define IDC_UNIT_RADIAN                 1226
#define IDC_EVENTOUT_NODE               1227
#define IDC_EVENTOUT_FIELD              1228
#define IDC_TEXT_NAME                   1229
#define IDC_BACKGROUND_NAME             1230
#define IDC_IMAGETEXTURE_NAME           1231
#define IDC_SWITCH_NAME                 1232
#define IDC_EVENTIN_NODE                1233
#define IDC_EVENTIN_FIELD               1234
#define ID_SCENEGRAPH_LOAD              32771
#define ID_SCENEGRAPH_SAVE              32772
#define ID_SCENEGRAPH_SAVE_AS           32773
#define ID_DIAGRAM_NEW                  32774
#define ID_SIMULATION_GO                32775
#define ID_SIMULATION_STOP              32776
#define ID_EVENT_NEW                    32778
#define ID_SIMULATION_STEP              32783
#define ID_SIMULATION_PAUSE             32785
#define ID_FONT_SETTING                 32789
#define ID_UNDO                         32794
#define ID_SCENEGRAPH_NEW               32795
#define ID_WALKING                      32799
#define ID_PICKING                      32802
#define ID_RENDERING_WIREFRAME          32803
#define ID_RENDERING_SHADE              32804
#define ID_ZOOMVIEW                     32808
#define ID_HEADLIGHT                    32809
#define ID_BUTTON32810                  32810
#define ID_ZOOMALL                      32810
#define ID_OBJECT_ZOOM                  32811
#define ID_OBJECT_MOVE                  32813
#define ID_OBJECT_PICK                  32814
#define ID_XY_VIEW                      32815
#define ID_YZ_VIEW                      32817
#define ID_XZ_VIEW                      32819
#define ID_NODE_NEW                     32820
#define ID_GRID                         32821
#define ID_SNAP                         32822
#define ID_RENDERING_TEXTURE            32824
#define ID_3DWINDOW                     32825
#define ID_2DWINDOW                     32826
#define ID_CONFIG                       32828
#define ID_OBJECT_ROTATE                32829
#define ID_ABOUTBOX                     32830
#define ID_BUTTON32831                  32831
#define ID_DIAGRAM_CONFIG               32832
#define ID_VIEWCHANGE                   32836
#define ID_VIEW_CHANGE                  32838
#define ID_PAN                          32839
#define ID_SLIDE                        32841
#define ID_ROTATE                       32842
#define IDS_SCENEGRAPH_NEW              32843
#define ID_MENUITEM_PICK                32848
#define ID_MENUITEM_MOVE                32853
#define ID_MENUITEM_ROTATE              32854
#define ID_MENUITEM_ZOOM                32855
#define ID_MENUITEM_XYPLANE             32856
#define ID_MENUITEM_YZPLANE             32857
#define ID_MENUITEM_XZPLANE             32858
#define ID_MENUITEM_WALK                32860
#define ID_MENUITEM_ROT                 32861
#define ID_MENUITEM_PAN                 32862
#define ID_MENUITEM_WIREFRAME           32863
#define ID_MENUITEM_SHADING             32864
#define ID_MENUITEM_TEXTURING           32865
#define ID_ROUTE_NEW                    32878
#define ID_BUTTON32879                  32879
#define ID_BUTTON32880                  32880
#define ID_BUTTON32881                  32881
#define ID_BUTTON32882                  32882
#define IDS_EDIT_PASTE                  57636
#define IDS_SCENEGRAPH_DELETE_TREENODE  61446

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        381
#define _APS_NEXT_COMMAND_VALUE         32883
#define _APS_NEXT_CONTROL_VALUE         1233
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
